name: Go

on:
  push:
    branches: [ "main", "feat/ci"]
  pull_request:
    branches: [ "main", "develop/pass" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Test
        run: make unit-tests
