name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop/pass" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Unit Test
        run: make unit-tests

      - name: e2e Test
        run: make ci-e2e
